name: Auto Deploy to Windows Server

on:
  push:
    branches:
      - master   # Nhánh bạn muốn kích hoạt auto deploy

jobs:
  deploy:
    runs-on: self-hosted   # Chỉ định chạy trực tiếp trên Windows Server

    steps:
      - name: Deploy Code
        run: |
          cd D:\code\homechicken
          git pull origin master
          
          npm install
          pm2 restart all
          